### ISSUE TITLE
CircleCI: Add test checking that s4ext are valid

### ISSUE THREAD

**Issue by jcfr** [Slicer/ExtensionsIndex#1557]
Each time a PR is submitted, a test should check the format of the description file.

**Comment by pieper** [comment]
Maybe we can find a way to actually build an extension on a CI using one of the slicer build dockers as the base?

**Comment by pieper** [comment]
@sjh26 and I were discussing this in the context of [this issue](https://github.com/Slicer/ExtensionsIndex/issues/1583) where the s4ext file pointed to a git hash that didn't even have a CMakeLists.txt file, but the log info was only on the factory machine.  If we tried to build the extension as part of CI then the extension contributor would be able to investigate independently.

**Comment by jcfr** [comment]
Closing this issue. 

It was addressed by adding tests running using CircleCI: https://github.com/Slicer/ExtensionsIndex/commits/master/.circleci

* https://github.com/Slicer/ExtensionsIndex/blob/master/scripts/check_filenames.sh
* https://github.com/Slicer/ExtensionsIndex/blob/master/scripts/check_description_files.py

![image](https://user-images.githubusercontent.com/219043/46292320-a1fb5180-c55e-11e8-921d-05c72ce4d8dd.png)
