### ISSUE TITLE
SlicerCochlea does not appear in the extension manager 

### ISSUE THREAD

**Issue by idhamari** [Slicer/ExtensionsIndex#1583]
Its been a week now and the extension is not available in Slicer 4.8.1 extension manager. I need it because I want to make a video tutorial about installing Slicer and the extension.

**Comment by pieper** [comment]
@idhamari it looks like this s4ext is only in the master, not the 4.8 branch so it would only be in the nightly slicer.

But I'm not seeing anything on [the dashboard](http://slicer.cdash.org/index.php?project=SlicerPreview) for this extension so I wonder if it's failing early or not being recognized.  The [SkeletalRepresentation](https://github.com/Slicer/ExtensionsIndex/blob/master/SkeletalRepresentation.s4ext) extension was added at a similar time and it shows up on the dashboard.

Maybe @jcfr or someone else at Kitware can look at the factory machines to see what's happening with this extension.

**Comment by idhamari** [comment]
Thanks for your reply. I just made a new pull request in the 4.8 branch. I didn't follow the extension code standard, probably this will cause failure. I will modify the code and implement the testing class soon.

**Comment by idhamari** [comment]
Thanks for your information. In my file it looks like this:

scmurl https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea
scmrevision 48e37f9

what should I change?

**Comment by sjh26** [comment]
There are two main options

One (and the one I would recommend for you):
scmrevision master
This will build always use the most recent commit to build for the extension manager.  Quick and convenient if you are actively developing and want the newest version to be built every time.  This works best if your are not committing directly to the master branch, but instead work on separate topic branches and only merge them when they are complete and functioning.

Two:
scmrevision daa2eca
Specifying a commit tag will have the extension manager always build that code version, even if there are newer ones available.  You would need to make a PR each time you want to update the revision the extension manager uses.  This is useful if you are continuing to work on your master branch, but want to precisely control when the extension manager changes. The specific tag i have used here is the latest one from your repo.

**Comment by idhamari** [comment]
Thanks for the detailed information. I just modified the file using

    scmrevision master

I mad new pull requests. please delete the last one and keep the two most recent.
