### ISSUE TITLE
Failed to register TorchIO extension

### ISSUE THREAD

**Issue by fepegar** [Slicer/ExtensionsIndex#1705]
Hi all,

I'm not sure if I should post this here, on Discourse or on the Slicer GitHub. Happy to move the discussion somewhere else, if you prefer.

I'm trying to contribute [my extension](https://github.com/fepegar/SlicerTorchIO) by following [these instructions](https://www.slicer.org/wiki/Documentation/Nightly/Developers/ExtensionWizard), but I'm getting an error:

```
$ slicerExtensionWizard --contribute --target master .
obtaining github repository information
failed to register extension: 404 {"message": "Not Found", "documentation_url":
"https://developer.github.com/v3/repos/#get"}
```

**Comment by jcfr** [comment]
Thanks for the issue report.  I will shortly try to reproduce this and will follow up.

**Comment by fepegar** [comment]
Thanks @jcfr! Let me know if you need me to try anything else.

**Comment by jcfr** [comment]
Few updates;

Running `slicerExtensionWizard --contribute .` I was able to create https://github.com/Slicer/ExtensionsIndex/pull/1707

Running `slicerExtensionWizard --contribute --target master .`, I was able to create https://github.com/Slicer/ExtensionsIndex/pull/1708

Do you have credential help setup ? On my workstation I have:

```
$ git config credential.helper
cache
```

But to make things easier (as I have two factor authentication setup), I simply export the environment variable `GITHUB_TOKEN`.

And to avoid setting this env. globally, I created this convenient script:

```
cat  /home/jcfr/bin/slicerExtensionWizard
#/usr/bin/env bash 

set -e
set -o pipefail

export GITHUB_TOKEN=$GH_CMDLINE_TOKEN

/home/jcfr/Projects/Slicer-Release/Slicer-build/bin/slicerExtensionWizard "$@"
```

**Comment by jcfr** [comment]
To allow you to create the PR, I closed the ones I created myself while testing this.

**Comment by fepegar** [comment]
Credentials (macOS):

```
$ git config credential.helper
osxkeychain
```

**Comment by fepegar** [comment]
Would you like me to try on Linux?

**Comment by jcfr** [comment]
Copying here comment from  @lassoan  originally posted at https://github.com/Slicer/ExtensionsIndex/pull/1709#issuecomment-639810826:

> This extension looks very interesting but I have no idea what it can do and how to use it. If this commit is only for testing if it builds then it's fine, but if we want to give a chance for users to discover and be able to use this extension then we need to complete the extension checklist.

**Comment by jcfr** [comment]
@fepegar  Could you try again after forking https://github.com/Slicer/ExtensionsIndex ?

**Comment by fepegar** [comment]
@lassoan This is my first extension ever, I'm just seeing if everything works fine. I didn't know about the [checklist](https://github.com/Slicer/ExtensionsIndex/blob/master/.github/PULL_REQUEST_TEMPLATE.md), I just googled it after reading your comment. Should I fork the ExtensionsIndex and try again now or keep working on the checklist until it's better prepared to be uploaded?

**Comment by fepegar** [comment]
By the way, the idea is that the extension is a GUI for [this library](https://github.com/fepegar/torchio), so users can quickly try transforms before implementing them in their deep learning applications.

**Comment by jcfr** [comment]
There are two things:

* issue with the extension wizard

* improvement of the extension metadata, etc ... 

> Should I fork the ExtensionsIndex and try again now

yes. 

>  keep working on the checklist

This will be done after the PR is created, we will be able to comment and have discussion in the PR

**Comment by jcfr** [comment]
Thanks for your patience 🙏

**Comment by jcfr** [comment]
I also realized that we need to update the instruction and remove the use of the wizard, it is redundant with what is at the end of the list here: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions#Step-by-step:_How_to_create.2C_publish.2C_distribute_and_maintain_an_extension_.3F

**Comment by jcfr** [comment]
I edited the wiki page to explicitly reference the checklist: https://www.slicer.org/w/index.php?title=Documentation%2FNightly%2FDevelopers%2FTutorials%2FBuildTestPackageDistributeExtensions&type=revision&diff=63283&oldid=60686

**Comment by lassoan** [comment]
@fepegar This will be great, just address the checklist items before you announce it or start advertising it .

**Comment by fepegar** [comment]
PR created after forking: https://github.com/Slicer/ExtensionsIndex/pull/1710

Should I add the checklist to the PR message?

**Comment by lassoan** [comment]
> Should I add the checklist to the PR message?

Yes, please.

**Comment by fepegar** [comment]
Closing as the extension has been successfully added.
