### ISSUE TITLE
trying to add auto3dgm extension to slicer

### ISSUE THREAD

**Issue by sshanshans** [Slicer/ExtensionsIndex#1711]
Hi Slicer community, 
We created a pull request #1701  a while ago, where we tried to add an extension to Slicer. We have made changes to our package according to the feedback we got from the first round of review. However, we haven't heard anything back since mid may. Could you kindly let me know is there any further changes we should make to our package here to make it available? 
I have committed a new file of _auto3dgm.s4ext_ under the same pull request. 

Thank you so much for your time and help!
Shan Shan

**Comment by lassoan** [comment]
The extension is merged now. Thank you for your contribution!
