### ISSUE TITLE
Icon and description in Extensions Manager

### ISSUE THREAD

**Issue by FredericBr** [Slicer/ExtensionsIndex#1712]
Hi @jcfr 
We already spoke about this issue, but the problem remains.
Although my ExtensionsIndex/GeodesicSlicer.s4ext file was updated, GeodesicSlicer doesn't have the picture (icon) and the good description in 3D Slicer "Extensions Manager".

Can you tell me how to figure this issue out?

Thank you,

Frederic

**Comment by jamesobutler** [comment]
Frederic, it appears you need to update various links in the GeodesicSlicer.s4ext file here in this repo.

https://github.com/Slicer/ExtensionsIndex/blob/d928453b8642f3c984274cda914192de9b1ff6c4/GeodesicSlicer.s4ext#L30-L31

You can use this other extension as an example of what it should be like:
https://github.com/Slicer/ExtensionsIndex/blob/master/SegmentEditorExtraEffects.s4ext

You will want to issue a PR to update the GeodesicSlicer.s4ext file for both the master branch (for Slicer Preview build) and the 4.10 branch if you want it updated for the extensions manager in Slicer 4.10.2.

**Comment by FredericBr** [comment]
Thanks @jamesobutler .
I changed my files into the 2 branches. Hope it will work!
Frederic

**Comment by jamesobutler** [comment]
Icon and description are now as desired.  The following updates were completed:
https://github.com/FredericBr/SlicerGeodesic/commit/8b943799484faa6d9511aab6ef8b933860a2e96c
https://github.com/Slicer/ExtensionsIndex/commit/10119fb1db24aeb8c576c51f616b135d8368fd55
https://github.com/Slicer/ExtensionsIndex/commit/1c51ead2512e3f89eeddaa0ef488432895229cf8

![image](https://user-images.githubusercontent.com/15837524/84705414-5c94d880-af29-11ea-8ce2-cde26763a307.png)
![image](https://user-images.githubusercontent.com/15837524/84705471-6ddde500-af29-11ea-9b7b-276ad6d91cbd.png)

**Comment by FredericBr** [comment]
Great!
Thanks once again.
