### ISSUE TITLE
SpineSegmentation - Add extension

### ISSUE THREAD

**Issue by jcfr** [Slicer/ExtensionsIndex#18]
Contact: Sylvain J.
http://wiki.na-mic.org/Wiki/index.php/2010_Winter_Project_Week_Spine_Segmentation_Module_in_Slicer3

**Comment by idhamari** [comment]
I am interested in this work. Is there anything I can do?

**Comment by pieper** [comment]
I don't believe this is being actively developed, but you can feel free to pick up the pieces and port to the latest software versions.

**Comment by sjh26** [comment]
@jcfr Can these 2012 backlogs be closed?
