### ISSUE TITLE
ExtraMarkups is not built for Slicer 5.2.2

### ISSUE THREAD

**Issue by chir-set** [Slicer/ExtensionsIndex#1915]
Hi,

Extension manager in Slicer 5.2.2 stable does not list ExtraMarkups. cdash neither.

It is still available for Slicer preview.

Is there an issue I should fix ?

Thank you.

**Comment by jamesobutler** [comment]
https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#distribute-an-extension

> Add your .s4ext file to your forked repository: it can be done using a git client or simply by clicking ‘’Upload files’’ button
> To make the extension appear in the latest Slicer Preview Release: upload the file into the master branch.
> To make the extension appear in the latest Slicer Stable Release: upload the file into the branch corresponding to the stable release version, for example: 4.10.

Therefore you will need to issue a PR to add [SlicerExtraMarkups.s4ext](https://github.com/Slicer/ExtensionsIndex/blob/main/SlicerExtraMarkups.s4ext) to the `5.2` branch (https://github.com/Slicer/ExtensionsIndex/tree/5.2) for it to be available in the latest Stable which is Slicer 5.2.x.

**Comment by chir-set** [comment]
Thank you very much, I didn't know a new [PR](https://github.com/Slicer/ExtensionsIndex/pull/1916) must be submitted for a stable branch.
